### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by mfiers** [aertslab/arboreto#1]
Hey - 
Not sure if this is an issue - but after using grnboost for 16 hours on 200 cpu's i got this error message:
```
distributed.utils - ERROR - ('infer_data-c4dbee66e029628605e1f69c6886d80d', 'tcp://10.132.0.10:42063')     
Traceback (most recent call last):                     
  File "/opt/miniconda3/lib/python3.6/site-packages/distributed/utils.py", line 238, in f                      
    result[0] = yield make_coro()                      
  File "/opt/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run                         
    value = future.result()                            
  File "/opt/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run                         
    yielded = self.gen.throw(*exc_info)                
  File "/opt/miniconda3/lib/python3.6/site-packages/distributed/client.py", line 1364, in _gather              
    traceback)                                         
  File "/opt/miniconda3/lib/python3.6/site-packages/six.py", line 693, in reraise                              
    raise value                                        
distributed.scheduler.KilledWorker: ('infer_data-c4dbee66e029628605e1f69c6886d80d', 'tcp://10.132.0.10:42063') 
Traceback (most recent call last):                     
  File "./run_grnboost.py", line 60, in <module>       
    client_or_address=cluster_client)                  
  File "/opt/miniconda3/lib/python3.6/site-packages/arboretum/algo.py", line 71, in genie3                     
    limit=limit, seed=seed, verbose=verbose)           
  File "/opt/miniconda3/lib/python3.6/site-packages/arboretum/algo.py", line 129, in diy                       
    .compute(graph, sync=True) \                       
  File "/opt/miniconda3/lib/python3.6/site-packages/distributed/client.py", line 2232, in compute              
    result = self.gather(futures)                      
  File "/opt/miniconda3/lib/python3.6/site-packages/distributed/client.py", line 1486, in gather               
    asynchronous=asynchronous)                         
  File "/opt/miniconda3/lib/python3.6/site-packages/distributed/client.py", line 608, in sync                  
    return sync(self.loop, func, *args, **kwargs)      
  File "/opt/miniconda3/lib/python3.6/site-packages/distributed/utils.py", line 254, in sync                   
    six.reraise(*error[0])                             
  File "/opt/miniconda3/lib/python3.6/site-packages/six.py", line 693, in reraise                              
    raise value                                        
  File "/opt/miniconda3/lib/python3.6/site-packages/distributed/utils.py", line 238, in f                      
    result[0] = yield make_coro()                      
  File "/opt/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run                         
    value = future.result()                            
  File "/opt/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run                         
    yielded = self.gen.throw(*exc_info)                
  File "/opt/miniconda3/lib/python3.6/site-packages/distributed/client.py", line 1364, in _gather              
    traceback)                                         
  File "/opt/miniconda3/lib/python3.6/site-packages/six.py", line 693, in reraise                              
    raise value                                        
distributed.scheduler.KilledWorker: ('infer_data-c4dbee66e029628605e1f69c6886d80d', 'tcp://10.132.0.10:42063') 
```

**Comment by tmoerman** [comment]
Insufficient info to diagnose this problem.
Ref: https://stackoverflow.com/questions/46691675/what-do-killedworker-exceptions-mean-in-dask
