### ISSUE TITLE
requirements.txt is missing from PyPI source tarball

### ISSUE THREAD

**Issue by boegel** [aertslab/arboreto#33]
`requirements.txt` is required by `setup.py`, but it's missing from the PyPI source tarball, which leads to the following when trying to install `arboreto` 0.1.6 from source:
```
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/eb-hq4sf4y2/pip-req-build-q_upe322/setup.py", line 17, in <module>
        install_requires=read_requirements('requirements.txt'),
      File "/tmp/eb-hq4sf4y2/pip-req-build-q_upe322/setup.py", line 4, in read_requirements
        with open(fname, 'r', encoding='utf-8') as file:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by felipehidra** [comment]
Same issue here!

**Comment by naddsch** [comment]
I am also running into that issue when trying to install from github
